create table T_STATION
(
    ID INTEGER,
    STOP_STATION INTEGER NOT NULL,
    STOP_NAME VARCHAR(200) NOT NULL
);
ALTER TABLE T_STATION ADD CONSTRAINT C_PK_STATION PRIMARY KEY (ID);
CREATE SEQUENCE S_STATION_ID;
